{
 "title": "Watchtower",
 "description": "Watchtower metrics",
 "tags": [
  "watchtower",
  "docker"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total Scans",
   "type": "stat",
   "gridPos": { "h": 4, "w": 1, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "watchtower_scans_total" }
   ]
  },
  {
   "title": "Container Updates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 1, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "watchtower_containers_scanned" },
    { "expr": "watchtower_containers_failed" },
    { "expr": "watchtower_containers_updated" }
   ]
  },
  {
   "title": "Skipped Scans",
   "type": "stat",
   "gridPos": { "h": 4, "w": 1, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "watchtower_scans_skipped" }
   ]
  }
 ]
}